/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import static Forms.Main.apuestas;
import static Forms.Main.lista;
import Herramientas.Archivo;
import Herramientas.ControlCaballo;
import Herramientas.Controlador;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author emili
 */
public class Inicio extends javax.swing.JFrame  {

    /**
     * Creates new form Inicio
     */
    BufferedImage fondo = ImageIO.read(new File("src/main/java/Imagenes/Fondo.jpg"));
    
    public Inicio()throws IOException {
        initComponents();
        jLabel1.setIcon(new ImageIcon(fondo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IngresoApuesta = new javax.swing.JButton();
        VerificarApuesta = new javax.swing.JButton();
        Resultados = new javax.swing.JButton();
        SubirArchivo = new javax.swing.JButton();
        CerrarApuesta = new javax.swing.JButton();
        Entradatxt = new javax.swing.JTextArea();
        salir1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IngresoApuesta.setBackground(new java.awt.Color(255, 204, 102));
        IngresoApuesta.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        IngresoApuesta.setText("Ingresar Apuesta");
        IngresoApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoApuestaActionPerformed(evt);
            }
        });
        jPanel1.add(IngresoApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 150, 60));

        VerificarApuesta.setBackground(new java.awt.Color(255, 204, 102));
        VerificarApuesta.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        VerificarApuesta.setText("Verificar");
        VerificarApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarApuestaActionPerformed(evt);
            }
        });
        jPanel1.add(VerificarApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 150, 60));

        Resultados.setBackground(new java.awt.Color(255, 204, 102));
        Resultados.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        Resultados.setText("Resultados");
        Resultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadosActionPerformed(evt);
            }
        });
        jPanel1.add(Resultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 150, 60));

        SubirArchivo.setBackground(new java.awt.Color(255, 204, 102));
        SubirArchivo.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        SubirArchivo.setText("Cargar Archivo");
        SubirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(SubirArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 150, 60));

        CerrarApuesta.setBackground(new java.awt.Color(255, 204, 102));
        CerrarApuesta.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        CerrarApuesta.setText("Cerrar Apuestas");
        CerrarApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarApuestaActionPerformed(evt);
            }
        });
        jPanel1.add(CerrarApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 150, 60));

        Entradatxt.setBackground(new java.awt.Color(255, 204, 153));
        Entradatxt.setColumns(20);
        Entradatxt.setRows(5);
        Entradatxt.setText("SE VISUALIZARAN LOS DATOS INGRESADOS ATRAVEZ DE UN ARCHIVO...");
        jPanel1.add(Entradatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 550, 500));

        salir1.setBackground(new java.awt.Color(255, 153, 102));
        salir1.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        salir1.setText("Salir");
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });
        jPanel1.add(salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, 130, 60));

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel2.setText("HIPODROMO SERVICIO DE APUESTAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresoApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoApuestaActionPerformed
        // TODO add your handling code here:
         if (apuestas == true) {
          try {
                   new IngresarDatos().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
        } else {
            JOptionPane.showMessageDialog(null, " LAS APUESTAS ESTAN CERRADAS");
        }
    }//GEN-LAST:event_IngresoApuestaActionPerformed

    private void ResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadosActionPerformed
        // TODO add your handling code here:
          try {
                    new Resultados().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_ResultadosActionPerformed

    private void SubirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirArchivoActionPerformed
        // TODO add your handling code here:
         if (apuestas == true) {
            Archivo archE = new Archivo();
            String[] cadena = archE.SubirArchivo(this);
            Controlador liso= new Controlador();
            Controlador lisoE= new Controlador();
            ControlCaballo cc = new ControlCaballo();
            Main.errores=lisoE;
            lista = cc.validacionCaballos(cadena, liso);
            int Datos=lista.tamañoArreglo();
            JOptionPane.showMessageDialog(null,"Se ingresaron "+ Datos+" filas");
        }else{
            JOptionPane.showMessageDialog(null, "ACTUALMENTE ESTAN CERRADAS LAS APUESTAS");
        }
        
    }//GEN-LAST:event_SubirArchivoActionPerformed

    private void CerrarApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarApuestaActionPerformed
        // TODO add your handling code here:
           apuestas=false;                                                 
        JOptionPane.showMessageDialog(null, "Hemos analizado las apuestas, recuerda ingresar los resultado\n"+
                                                         "no olvides ingresar los resultados");          
                                               
        JOptionPane.showMessageDialog(null, "\tA Continuacion te enviamos el archivo\n\tde las apuestas que han tenido errores y\n\tno se han tomado en cuenta");
        lista=lista.analizarApuestas();
        lista.tamañoArreglo();                                    
        Main.errores.tamañoArreglo();
                                                                //----------------
                                                                        //n
    }//GEN-LAST:event_CerrarApuestaActionPerformed

    private void VerificarApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarApuestaActionPerformed
        // TODO add your handling code here:
         lista=lista.analizarApuestas();  
     
    }//GEN-LAST:event_VerificarApuestaActionPerformed

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Inicio().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarApuesta;
    private javax.swing.JTextArea Entradatxt;
    private javax.swing.JButton IngresoApuesta;
    private javax.swing.JButton Resultados;
    private javax.swing.JButton SubirArchivo;
    private javax.swing.JButton VerificarApuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salir1;
    // End of variables declaration//GEN-END:variables
}
