/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import static Forms.Main.apuestas;
import static Forms.Main.lista;
import Herramientas.Archivo;
import Herramientas.ControlCaballo;
import javax.swing.JOptionPane;

/**
 *
 * @author emili
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IngresoApuesta = new javax.swing.JButton();
        VerificarApuesta = new javax.swing.JButton();
        Resultados = new javax.swing.JButton();
        SubirArchivo = new javax.swing.JButton();
        CerrarApuesta = new javax.swing.JButton();
        Entradatxt = new javax.swing.JTextArea();
        salir1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IngresoApuesta.setText("Ingresar Apuesta");
        IngresoApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoApuestaActionPerformed(evt);
            }
        });
        jPanel1.add(IngresoApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 150, 60));

        VerificarApuesta.setText("Verificar");
        VerificarApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarApuestaActionPerformed(evt);
            }
        });
        jPanel1.add(VerificarApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 150, 60));

        Resultados.setText("Resultados");
        Resultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadosActionPerformed(evt);
            }
        });
        jPanel1.add(Resultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 150, 60));

        SubirArchivo.setText("Cargar Archivo");
        SubirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(SubirArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 150, 60));

        CerrarApuesta.setText("Cerrar Apuestas");
        CerrarApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarApuestaActionPerformed(evt);
            }
        });
        jPanel1.add(CerrarApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, 150, 60));

        Entradatxt.setColumns(20);
        Entradatxt.setRows(5);
        jPanel1.add(Entradatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 600, 540));

        salir1.setText("Salir");
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });
        jPanel1.add(salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, 130, 60));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresoApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoApuestaActionPerformed
        // TODO add your handling code here:
         if (apuestas == true) {
            IngresarDatos ingreso = new IngresarDatos();
            ingreso.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "ACTUALMENTE LAS APUESTAS ESTAN CERRADAS");
        }
    }//GEN-LAST:event_IngresoApuestaActionPerformed

    private void ResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadosActionPerformed
        // TODO add your handling code here:
         Resultados R= new Resultados();
        R.setVisible(true);
    }//GEN-LAST:event_ResultadosActionPerformed

    private void SubirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirArchivoActionPerformed
        // TODO add your handling code here:
           if (apuestas == true) {
            Archivo Entrada = new Archivo();
            String[] cadena = Entrada.SubirArchivo(this);
            ControlCaballo cc = new ControlCaballo();
            lista = cc.validacionCaballos(cadena, lista);
            System.out.println("----------->");
            lista.Imprimir();
        }else{
            JOptionPane.showMessageDialog(null, "ACTUALMENTE ESTAN CERRADAS LAS APUESTAS");
        }
        
        
    }//GEN-LAST:event_SubirArchivoActionPerformed

    private void CerrarApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarApuestaActionPerformed
        // TODO add your handling code here:
          apuestas=false;
        JOptionPane.showMessageDialog(null, "Analisis de apuestas automatico\n"+
                                                         "Las apuestas se han cerrado correctamente");
       lista=lista.analizarApuestas();                                       //O(n)
        lista.Imprimir();                                      //O(n)
        Main.errores.Imprimir();
    }//GEN-LAST:event_CerrarApuestaActionPerformed

    private void VerificarApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarApuestaActionPerformed
        // TODO add your handling code here:
         lista=lista.analizarApuestas();  
     
    }//GEN-LAST:event_VerificarApuestaActionPerformed

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarApuesta;
    private javax.swing.JTextArea Entradatxt;
    private javax.swing.JButton IngresoApuesta;
    private javax.swing.JButton Resultados;
    private javax.swing.JButton SubirArchivo;
    private javax.swing.JButton VerificarApuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salir1;
    // End of variables declaration//GEN-END:variables
}
